// <auto-generated />
namespace BS_FormBuilder.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FontSupportAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FontSupportAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201408260926554_Font Support Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
