// <auto-generated />
namespace BS_FormBuilder.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class OpenDialogButtonPosition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OpenDialogButtonPosition));
        
        string IMigrationMetadata.Id
        {
            get { return "201408261329292_Open Dialog Button Position"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
